//! Emit the chart's CRD manifest.
//!
//! Deliberately thin: every rule about what a CRD must look like lives in [`updatec::crd`], so the
//! YAML an operator converges is generated by the same code the tests check.

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let documents: Vec<String> = updatec::crd::all()
        .iter()
        .map(serde_yaml::to_string)
        .collect::<Result<_, _>>()?;
    print!("{}", documents.join("---\n"));
    Ok(())
}
